# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as ec, wait
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestConsultaCurso():
  def setup_method(self, method):
    self.driver = webdriver.Chrome('drivers/chrome/chromedriver100.exe')
    self.driver.implicitly_wait(2)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_consultaCurso(self):
    self.driver.get('https://iterasys.com.br/pt')
    self.driver.set_window_size(1552, 840)
    #self.driver.find_element(By.XPATH, '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[3]/button[2]/span[1]/span[1]').click()
    self.driver.find_element(By.XPATH, '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/a[1]/div[1]').click()
    print(f'Menu Cursos')

    assert self.driver.title == 'Cursos - Iterasys'
    print('Validou a aba Cursos')

    self.driver.find_element(By.XPATH, '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/main[1]/section[1]/div[1]/div[1]/div[1]/div[1]/main[1]/a[3]/main[1]/h3[1]').click()
    print(f'Achou o curso')

    #time.sleep(5)   # alfinete (deve sempre ser removida do codigo)
    #wait = WebDriverWait(self.driver, 3)
    #wait.until(ec.visibility_of_element_located(By.CSS_SELECTOR, 'h3.content-card-name.variant-primary'))

    assert self.driver.title == 'Formação em Teste de Software (Presencial) - Iterasys'
    print('Validou a aba do curso')
    assert self.driver.find_element(By.XPATH, '//h3[contains(text(),"Formação em Teste de Software (Presencial)")]').text == 'Formação em Teste de Software (Presencial)'
    print('Validou o nome do curso')
    assert self.driver.find_element(By.CSS_SELECTOR, 'p.content-price-installments-amount').text == 'R$ 499,00'
    print('Validou o valor do curso')
    # assert self.driver.find_element(By.CSS_SELECTOR, '.item-title').text == 'Mantis'
    # assert self.driver.find_element(By.CSS_SELECTOR, '.new-price').text == 'R$ 59,99'
